#include<iostream>
using namespace std;

/*
    What is a constructors?
        A constructors is a special type of method that is invoked each time that an object of a class is created.
    What is default constructors?
        Default constructors is a term to describe a constructor that is automatically generated by your compiler.
*/

// class တစ်ခု ကို ကိုယ်ပိုင် constructors မပါဘဲ့ create လုပ်လိုက်ရင် compiler သည် default constructors အနေနဲ့ class တွင်းမှာ ရှိတဲ့ methods(function) တွေကို auto invoke(call) လုပ်ပေးလိမ့်မယ်။
class Employee_default_constructors {
public:
    string Name;
    string Company;
    int Age;
    void IntroYourSelf() {
        cout << "Name : " << Name << endl;
        cout << "Company : " << Company << endl;
        cout << "Age : " << Age << endl;
    }
};

// ကိုယ် class ထဲမှာ ဖန်တီးလိုက်တဲ့ constructors သည် class ကို create လုပ်လိုက်တာနဲ့ ချက်ချင်း ကိုယ်ဖန်တီးထားတဲ့ constructors method ကို invoke လုပ်သည်။ ပြီးမှ ကျန်တဲ့ method တွေကို ဆက်လုပ်သည်။
class Employee_own_constructors {
public:
    string Name;
    string Company;
    int Age;
    void IntroYourSelf() {
        cout << "Name : " << Name << endl;
        cout << "Company : " << Company << endl;
        cout << "Age : " << Age << endl;
    }
    /*
        There are 3 rules to follow while creating own constructors
        - a own constructor not to be a return method (don't use data-type)
        - a own constructor has the same name of its belonging class
        - a own constructor must be created in public class
    */
    // ကိုယ်ပိုင်ဖန်တီးထားသော constructors
    // parameter ဘာမှမပေးလဲ method က စပြီး invoke လုပ်တယ်။
    Employee_own_constructors (string name, string company, int age) {
        Name = name;
        Company = company;
        Age = age;
    }
};

int main() {
    Employee_default_constructors employee_default;
    employee_default.Name = "SpongeBob";
    employee_default.Company = "KrastyCrab";
    employee_default.Age = 21;
    employee_default.IntroYourSelf();

    Employee_own_constructors employee_own("SquidWard", "KrastyCrab", 23);
    employee_own.IntroYourSelf();
    Employee_own_constructors employee_own_2 = Employee_own_constructors("Patrick", "idk", 21);
    employee_own_2.IntroYourSelf();
    return 0;
}